import './sync-write.mjs';
import { build } from 'esbuild';
import { cp, mkdir, readdir, readFile, writeFile } from 'node:fs/promises';
await mkdir('assets/vendor', { recursive: true });
const bundledPackages = new Set();
for (const [entry, outfile] of [['write/editor.js','assets/editor.js'], ['components/preview.js','assets/preview.js'], ['components/preview-worker.js','assets/preview-worker.js']]) {
  const result = await build({ metafile: true, entryPoints: [entry], outfile, bundle: true, format: 'esm', minify: true, target: 'es2022', legalComments: 'external' });
  for (const input of Object.keys(result.metafile.inputs)) { const dir = input.match(/^node_modules\/(?:@[^/]+\/)?[^/]+/)?.[0]; if (dir) bundledPackages.add(dir); }
}
let licenses = '';
for (const dir of [...bundledPackages].sort()) {
  const pkg = JSON.parse(await readFile(dir + '/package.json', 'utf8'));
  const file = (await readdir(dir)).find(name => /^license(?:\.|$)/i.test(name));
  licenses += `## ${pkg.name} ${pkg.version} (${pkg.license || 'See license'})\n\n${file ? await readFile(dir + '/' + file, 'utf8') : 'License notices included in distributed sources.'}\n\n`;
}
await writeFile('assets/vendor/THIRD-PARTY-LICENSES.txt', licenses);
await cp('node_modules/katex/dist/katex.min.css', 'assets/vendor/katex.min.css');
await cp('node_modules/katex/dist/fonts', 'assets/vendor/fonts', { recursive: true });
await cp('node_modules/highlight.js/styles/atom-one-dark.min.css', 'assets/vendor/highlight.min.css');
await writeFile('assets/vendor/README.md', 'Generated by npm run build. Dependency versions and integrity are recorded in package-lock.json. Bundles retain third-party license notices in .LEGAL.txt files. KaTeX fonts and CSS are distributed under the KaTeX MIT license.\n');
await cp('node_modules/katex/LICENSE', 'assets/vendor/KATEX-LICENSE.txt');

const shell = ['/write/', '/write/index.html', '/admin/index.html',
  '/write/write.js?v=20', '/write/pdf.js?v=20', '/write/page-mode.js?v=20', '/admin/admin.js?v=20',
  '/assets/editor.js?v=20', '/assets/preview.js?v=20', '/assets/preview-worker.js?v=20',
  '/components/drafts.js?v=20', '/components/editor-tools.js?v=20', '/components/mastodon.js?v=20',
  '/components/mastodon_oauth.js?v=20', '/assets/vendor/katex.min.css', '/assets/vendor/highlight.min.css'];
for (const font of await readdir('assets/vendor/fonts')) shell.push('/assets/vendor/fonts/' + font);
await writeFile('write/precache.json', JSON.stringify(shell, null, 2) + '\n');
